### ISSUE TITLE
Reporting exceptions

### ISSUE THREAD

**Issue by mcimbora** [radargun/radargun#219]
1.
[org.radargun.reporting.html.TimelineDocument](main) Failed to generate on of the charts: 
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 1000
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at org.radargun.reporting.html.TimelineDocument.writeTimelines(TimelineDocument.java:186)
        at org.radargun.reporting.html.HtmlReporter.writeTimelineDocuments(HtmlReporter.java:169)
        at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:50)
        at org.radargun.Master.run(Master.java:117)
        at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1000
        at org.radargun.reporting.html.TimelineChart.setEvents(TimelineChart.java:101)
        at org.radargun.reporting.html.TimelineDocument$1.call(TimelineDocument.java:131)
        at org.radargun.reporting.html.TimelineDocument$1.call(TimelineDocument.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

2.
[org.radargun.Master](main) Error in reporter org.radargun.reporting.html.HtmlReporter@5e838dcd
java.lang.NullPointerException
    at org.radargun.reporting.html.ReportDocument.writeResult(ReportDocument.java:146)
    at org.radargun.reporting.html.TestReportDocument.writeTest(TestReportDocument.java:51)
    at org.radargun.reporting.html.HtmlReporter.writeTestReportDocuments(HtmlReporter.java:152)
    at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:51)
    at org.radargun.Master.run(Master.java:117)

**Comment by vjuranek** [comment]
3.
```
 ERROR [org.radargun.reporting.html.TestReportDocument] (main) Failed to create chart
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Range(double, double): require lower (358602.0) <= upper (0.0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.radargun.reporting.html.ReportDocument.writeOperation(ReportDocument.java:291)
        at org.radargun.reporting.html.TestReportDocument.writeTest(TestReportDocument.java:63)
        at org.radargun.reporting.html.HtmlReporter.writeTestReportDocuments(HtmlReporter.java:152)
        at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:51)
        at org.radargun.Master.run(Master.java:117)
        at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
Caused by: java.lang.IllegalArgumentException: Range(double, double): require lower (358602.0) <= upper (0.0).
        at org.jfree.data.Range.<init>(Range.java:93)
        at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1318)
        at org.radargun.reporting.html.HistogramChart.createChart(HistogramChart.java:63)
        at org.radargun.reporting.html.Chart.save(Chart.java:23)
        at org.radargun.reporting.html.ReportDocument$4.call(ReportDocument.java:499)
        at org.radargun.reporting.html.ReportDocument$4.call(ReportDocument.java:493)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by vjuranek** [comment]
at least exception I posted seems to be related somehow to the build process, when I built just RG, I hit this exception, when build with JDG plugin, it runs fine
