### ISSUE TITLE
Bug in FreeMarker reporters

### ISSUE THREAD

**Issue by rvansa** [radargun/radargun#285]
@rmacor Could you look into this?

Thrown when running benchmark-cs.xml
```
12:32:36,732 ERROR [freemarker.runtime] (main) Error executing FreeMarker template
FreeMarker template error:
For ".." right-hand operand: Expected a number, but this has evaluated to a sequence (Collections$UnmodifiableRandomAccessList wrapped into f.t.DefaultListAdapter):
==> groups  [in template "timelineReport.ftl" at line 91, column 20]

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #list 0..groups as groupID  [in template "timelineReport.ftl" at line 91, column 10]
----

Java stack trace (for programmers):
----
freemarker.core.NonNumericalException: [... Exception message was already printed; see it above ...]
        at freemarker.core.Expression.modelToNumber(Expression.java:105)
        at freemarker.core.Expression.evalToNumber(Expression.java:98)
        at freemarker.core.Range._eval(Range.java:50)
        at freemarker.core.Expression.eval(Expression.java:78)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:69)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at freemarker.template.Template.process(Template.java:325)
        at org.radargun.reporting.html.HtmlReporter.processTemplate(HtmlReporter.java:240)
        at org.radargun.reporting.html.HtmlReporter.writeTimelineDocuments(HtmlReporter.java:189)
        at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:62)
        at org.radargun.Master.run(Master.java:135)
        at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
```

**Comment by mcimbora** [comment]
Fixed
