### ISSUE TITLE
StressorTest.testTransactional fails randomly

### ISSUE THREAD

**Issue by mcimbora** [radargun/radargun#312]

**Comment by mcimbora** [comment]
Unfortunately I don't have any additional log messages ATM.

**Comment by rvansa** [comment]
@mcimbora Is that all info you'll give me?

**Comment by mcimbora** [comment]
@rvansa Indeed. I wasn't able to reproduce it again.

**Comment by mcimbora** [comment]
java.lang.AssertionError: [statistics.finalize();, runningTest.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();, statistics.finalize();] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.radargun.stages.test.StressorTest.runSingleCycle(StressorTest.java:151)
	at org.radargun.stages.test.StressorTest.test(StressorTest.java:101)
	at org.radargun.stages.test.StressorTest.testTransactional(StressorTest.java:56)

**Comment by mcimbora** [comment]
@rvansa ^^
