### ISSUE TITLE
Master-slave communication stuck

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#319]
I spot following issue in master-slave communication in RG 2.X branch (not sure if present in RG3):
some slaves are properly started, but some got stuck, waiting for master (even worse not at the beginning of communication, it receives Configuration from master and then got stuck). My suspect is that RG master has wrong number expected responses for some reason and and waits for responses from other (non-existing) slaves in [slave communication loop](https://github.com/radargun/radargun/blob/master/core/src/main/java/org/radargun/RemoteSlaveConnection.java#L213). But I have to verify this hypothesis yet.

Part of the stack trace from RG master:
```
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x0000000716c475a0> (a sun.nio.ch.Util$2)
        - locked <0x0000000716c47518> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000716c460d0> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at org.radargun.RemoteSlaveConnection.flushBuffers(RemoteSlaveConnection.java:180)
        at org.radargun.RemoteSlaveConnection.runStage(RemoteSlaveConnection.java:162)
        at org.radargun.Master.executeDistStage(Master.java:236)
        at org.radargun.Master.executeStage(Master.java:144)
        at org.radargun.Master.run(Master.java:90)
        at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
```

Part of the stack trace from stuck slave:
```
java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        - locked <0x00000006c03118f0> (a java.lang.Object)
        at org.radargun.RemoteMasterConnection.readInt(RemoteMasterConnection.java:111)
        at org.radargun.RemoteMasterConnection.receiveObject(RemoteMasterConnection.java:127)
        at org.radargun.Slave.run(Slave.java:36)
        at org.radargun.Slave.main(Slave.java:67)
```

**Comment by mcimbora** [comment]
@vjuranek Do you have a reproducer for the issue by any chance (config file)?

**Comment by vjuranek** [comment]
@mcimbora [this Jenkins job](https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/BZ1279379/) seems to reproduce the issue in 100% cases (you can find config file in job config), however when running same scenario on my machine locally, I don't hit this issue.

**Comment by rvansa** [comment]
@vjuranek, is this resolved?

**Comment by vjuranek** [comment]
@rvansa I haven't tried recently, but IMHO not (at least I didn't noticed any commit which would address this issue)
