### ISSUE TITLE
java.lang.NullPointerException in Infinispan60ServerTopologyHistory

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#351]
```11:41:13,612 ERROR [org.radargun.service.Infinispan60ServerTopologyHistory] (pool-2-thread-2) Failed to retrieve data from JMX
java.lang.NullPointerException
	at org.radargun.service.Infinispan60ServerTopologyHistory.cacheStatus(Infinispan60ServerTopologyHistory.java:216) [plugin-infinispan60-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.Infinispan60ServerTopologyHistory.processCacheStatus(Infinispan60ServerTopologyHistory.java:67) [plugin-infinispan60-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.Infinispan60ServerTopologyHistory$1.run(Infinispan60ServerTopologyHistory.java:39) [plugin-infinispan60-3.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]```

**Comment by alanfx** [comment]
Fixes for this are in these PRs:
master - https://github.com/radargun/radargun/pull/352
branch_2.x - https://github.com/radargun/radargun/pull/350

**Comment by mcimbora** [comment]
Fixed

**Comment by mcimbora** [comment]
Fixed
