### ISSUE TITLE
Stressor test failures in master branch

### ISSUE THREAD

**Issue by mcimbora** [radargun/radargun#356]
@alanfx @rvansa Folks you should always run the tests before integrating any changes.

Tests run: 70, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 150.087 sec <<< FAILURE! - in TestSuite
testGetCheckedOperationIgnoreDeadCheckers(org.radargun.stages.cache.background.AbstractLogLogicTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.IllegalStateException: Slave index is -1, cluster is Cluster[group=2]
    at org.radargun.stages.cache.background.AbstractLogLogicTest.testGetCheckedOperationIgnoreDeadCheckers(AbstractLogLogicTest.java:160)

testGetCheckedOperationIgnoreDeadCheckersInitial1(org.radargun.stages.cache.background.AbstractLogLogicTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.IllegalStateException: Slave index is -1, cluster is Cluster[group=2]
    at org.radargun.stages.cache.background.AbstractLogLogicTest.testGetCheckedOperationIgnoreDeadCheckersInitial1(AbstractLogLogicTest.java:185)

testGetCheckedOperationNotPresentInCache(org.radargun.stages.cache.background.AbstractLogLogicTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.IllegalStateException: Slave index is -1, cluster is Cluster[group=2]
    at org.radargun.stages.cache.background.AbstractLogLogicTest.testGetCheckedOperationNotPresentInCache(AbstractLogLogicTest.java:145)

testGetCheckedOperationPresentInCache(org.radargun.stages.cache.background.AbstractLogLogicTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.IllegalStateException: Slave index is -1, cluster is Cluster[group=2]
    at org.radargun.stages.cache.background.AbstractLogLogicTest.testGetCheckedOperationPresentInCache(AbstractLogLogicTest.java:131)

smokeTestSharedKeys(org.radargun.stages.cache.background.BackgroundStressorsGeneralTest)  Time elapsed: 61.448 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.smokeTestSharedKeys() didn't finish within the time-out 60000
    at org.radargun.stages.cache.background.BackgroundStressorsGeneralTest.smokeTest(BackgroundStressorsGeneralTest.java:99)
    at org.radargun.stages.cache.background.BackgroundStressorsGeneralTest.smokeTestSharedKeys(BackgroundStressorsGeneralTest.java:28)

Results :

Failed tests: 
  AbstractLogLogicTest.testGetCheckedOperationIgnoreDeadCheckers:160 » IllegalState
  AbstractLogLogicTest.testGetCheckedOperationIgnoreDeadCheckersInitial1:185 » IllegalState
  AbstractLogLogicTest.testGetCheckedOperationNotPresentInCache:145 » IllegalState
  AbstractLogLogicTest.testGetCheckedOperationPresentInCache:131 » IllegalState ...
  BackgroundStressorsGeneralTest.smokeTestSharedKeys:28->smokeTest:99->Object.wait:-2 » ThreadTimeout

**Comment by alanfx** [comment]
Sorry, @mcimbora. Let me know if you want any help with this.

**Comment by jmarkos** [comment]
Tests seem to pass now, closing.
