### ISSUE TITLE
Exception while generating reports from serialized data

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#390]
Generating reports produced the following exception:

```
08:10:55,538 ERROR [org.radargun.reporting.html.TestReportDocument] (main) Failed to create chart
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: A positive range length is required: Range[6.0397977599E10,6.0397977599E10]
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.radargun.reporting.html.ReportDocument.waitForChartsGeneration(ReportDocument.java:329)
    at org.radargun.reporting.html.TestReportDocument.createTestCharts(TestReportDocument.java:66)
    at org.radargun.reporting.html.HtmlReporter.writeTestReportDocuments(HtmlReporter.java:177)
    at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:74)
    at org.radargun.reporting.serialized.SerializedReporter.main(SerializedReporter.java:102)
Caused by: java.lang.IllegalArgumentException: A positive range length is required: Range[6.0397977599E10,6.0397977599E10]
    at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1294)
    at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1272)
    at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1318)
    at org.radargun.reporting.html.HistogramChart.createChart(HistogramChart.java:48)
    at org.radargun.reporting.html.Chart.save(Chart.java:23)
    at org.radargun.reporting.html.ReportDocument$1.call(ReportDocument.java:85)
    at org.radargun.reporting.html.ReportDocument$1.call(ReportDocument.java:79)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
08:10:55,542 ERROR [org.radargun.reporting.html.TestReportDocument] (main) Failed to create chart
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: A positive range length is required: Range[6.0397977599E10,6.0397977599E10]
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.radargun.reporting.html.ReportDocument.waitForChartsGeneration(ReportDocument.java:329)
    at org.radargun.reporting.html.TestReportDocument.createTestCharts(TestReportDocument.java:66)
    at org.radargun.reporting.html.HtmlReporter.writeTestReportDocuments(HtmlReporter.java:177)
    at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:74)
    at org.radargun.reporting.serialized.SerializedReporter.main(SerializedReporter.java:102)
Caused by: java.lang.IllegalArgumentException: A positive range length is required: Range[6.0397977599E10,6.0397977599E10]
    at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1294)
    at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1272)
    at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1318)
    at org.radargun.reporting.html.HistogramChart.createChart(HistogramChart.java:48)
    at org.radargun.reporting.html.Chart.save(Chart.java:23)
    at org.radargun.reporting.html.ReportDocument$1.call(ReportDocument.java:85)
    at org.radargun.reporting.html.ReportDocument$1.call(ReportDocument.java:79)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

The values in the range are identical.

**Comment by alanfx** [comment]
@zhostasa I have not been able to find a reproducer for this. I'll close it for now until I do. Thanks
