### ISSUE TITLE
HTML reporters fail in some cases

### ISSUE THREAD

**Issue by rmacor** [radargun/radargun#394]
There is an error during HTML report creation.
to reproduce run the attached benchmark:
bin/dist.sh -t -c conf/benchmark-marshaller-server.xml test1 test2
[benchmark.zip](https://github.com/radargun/radargun/files/449401/benchmark.zip)

 ERROR [org.radargun.Master](main) Processing acks on master failed
java.lang.IllegalArgumentException: This stats don't have begin/end set correctly: PeriodicStatistics {beginTime=<none>, endTime=1472725962593}
    at org.radargun.stats.PeriodicStatistics.merge(PeriodicStatistics.java:136)
    at org.radargun.stats.MultiStatistics.merge(MultiStatistics.java:90)
    at org.radargun.stats.Statistics.with(Statistics.java:107)
    at org.radargun.stats.Statistics.lambda$static$0(Statistics.java:16)
    at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474)
    at org.radargun.stages.test.legacy.LegacyTestStage.processAckOnMaster(LegacyTestStage.java:125)
    at org.radargun.Master.executeDistStage(Master.java:277)
    at org.radargun.Master.executeStage(Master.java:164)
    at org.radargun.Master.run(Master.java:101)
    at org.radargun.LaunchMaster.main(LaunchMaster.java:34)

...

ERROR [org.radargun.Master](main) Error in reporter org.radargun.reporting.html.HtmlReporter@2f490758
java.lang.NullPointerException
    at org.radargun.reporting.html.ReportDocument.createHistogramAndPercentileChart(ReportDocument.java:71)
    at org.radargun.reporting.html.ReportDocument.createSingleHistogramAndPercentileCharts(ReportDocument.java:307)
    at org.radargun.reporting.html.ReportDocument.createHistogramAndPercentileCharts(ReportDocument.java:290)
    at org.radargun.reporting.html.TestReportDocument.createTestCharts(TestReportDocument.java:64)
    at org.radargun.reporting.html.HtmlReporter.writeTestReportDocuments(HtmlReporter.java:177)
    at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:74)
    at org.radargun.Master.run(Master.java:135)
    at org.radargun.LaunchMaster.main(LaunchMaster.java:34)

**Comment by alanfx** [comment]
This looks similar to https://github.com/radargun/radargun/issues/390

**Comment by zhostasa** [comment]
I did my best trying to reproduce the first error (second was fixed by @jmarkos) however I failed. @rmacor promised to give it another try when time allows.

**Comment by rmacor** [comment]
Can't reproduce this either, looks like it was already resolved. @zhostasa thanks for looking into it!
