### ISSUE TITLE
ClassCastException in org.radargun.utils.Fuzzy.next

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#403]
Seeing this running a benchmark with fuzzy entry sizes:

```
      <l:key-expiration-test duration="2m" num-threads-per-node="10"
                           entry-size="10%: 10, 20%: 100, 40%: 1000, 20%: 10000, 10: 100000"
                           num-bytes-per-thread="100 MB"
                           entry-lifespan="5s"
                           test-name="DistributedCache">
```

```
15:23:44,284 ERROR [org.radargun.stages.test.legacy.LegacyStressor] (Stressor-0) Unexpected error in stressor!
java.lang.ClassCastException: java.lang.Double cannot be cast to java.math.BigDecimal
	at java.math.BigDecimal.compareTo(BigDecimal.java:220)
	at java.util.Arrays.binarySearch0(Arrays.java:2439)
	at java.util.Arrays.binarySearch(Arrays.java:2379)
	at org.radargun.utils.Fuzzy.next(Fuzzy.java:67)
	at org.radargun.stages.cache.test.legacy.KeyExpirationTestStage$Logic.run(KeyExpirationTestStage.java:169)
	at org.radargun.stages.test.legacy.LegacyStressor.runInternal(LegacyStressor.java:108)
	at org.radargun.stages.test.legacy.LegacyStressor.run(LegacyStressor.java:65)
```

**Comment by alanfx** [comment]
@mgencur do you think this is related to your changes to Fuzzy?

**Comment by jmarkos** [comment]
I've hit this, too.

**Comment by mgencur** [comment]
@alanfx , yes, this is related. Let me fix it.

**Comment by mgencur** [comment]
PR: https://github.com/radargun/radargun/pull/408
