### ISSUE TITLE
ConfigDumpHelper throws AttributeNotFoundException exception

### ISSUE THREAD

**Issue by rmacor** [radargun/radargun#419]
Reproducible with attached benchmark config.
[benchmark.zip](https://github.com/radargun/radargun/files/519964/benchmark.zip)

ERROR [org.radargun.service.ConfigDumpHelper] (sc-main) Error while dumping ___protobuf_metadata cache config as properties
javax.management.AttributeNotFoundException: Unknown attribute 'configurationAsProperties'. Known attributes names are: [rebalancingEnabled, cacheStatus, cacheName, cacheAva
ilability, version, configurationAsProperties]
        at org.infinispan.jmx.ResourceDMBean.getAttribute(ResourceDMBean.java:181) ~[infinispan-core-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647) ~[?:1.8.0_76-ea]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678) ~[?:1.8.0_76-ea]
        at org.radargun.service.ConfigDumpHelper60.dumpCache(ConfigDumpHelper60.java:44) [plugin-infinispan60-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.service.EmbeddedConfigurationProvider.getNormalizedConfigs(EmbeddedConfigurationProvider.java:33) [plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.stages.lifecycle.ServiceStartStage.executeOnSlave(ServiceStartStage.java:92) [radargun-core-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:90) [radargun-core-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158) [radargun-core-3.0.0-SNAPSHOT.jar:?]
12:22:20,400 ERROR [org.radargun.service.ConfigDumpHelper] (sc-main) Error while dumping ___protobuf_metadata cache config as properties
javax.management.AttributeNotFoundException: Unknown attribute 'configurationAsProperties'. Known attributes names are: [rebalancingEnabled, cacheStatus, cacheName, cacheAva
ilability, version, configurationAsProperties]
        at org.infinispan.jmx.ResourceDMBean.getAttribute(ResourceDMBean.java:181) ~[infinispan-core-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647) ~[?:1.8.0_76-ea]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678) ~[?:1.8.0_76-ea]
        at org.radargun.service.ConfigDumpHelper60.dumpCache(ConfigDumpHelper60.java:44) [plugin-infinispan60-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.service.EmbeddedConfigurationProvider.getNormalizedConfigs(EmbeddedConfigurationProvider.java:33) [plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.stages.lifecycle.ServiceStartStage.executeOnSlave(ServiceStartStage.java:92) [radargun-core-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:90) [radargun-core-3.0.0-SNAPSHOT.jar:?]
        at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158) [radargun-core-3.0.0-SNAPSHOT.jar:?]

**Comment by jmarkos** [comment]
Will be fixed by https://issues.jboss.org/browse/ISPN-7128

**Comment by jmarkos** [comment]
Fixed in latest infinispan snapshot.
