### ISSUE TITLE
AbstractConfigurationTest fails randomly with InstantiationException

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#430]
```
[ERROR] Error creating object factory: class org.radargun.config.AbstractConfigurationTest
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:84)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:413)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:239)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:209)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:157)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:546)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:159)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1274)
[ERROR] at org.testng.TestNG.createSuiteRunners(TestNG.java:1261)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1115)
[ERROR] at org.testng.TestNG.run(TestNG.java:1032)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.InstantiationException
[ERROR] at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:75)
[ERROR] ... 18 more
```

**Comment by vjuranek** [comment]
@zhostasa states that @jmarkos states that this one is fixed, therefor closing as I trust my colleagues :-)
