### ISSUE TITLE
HtmlReporter fails with ConcurrentModificationException

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#434]
```
08:52:08,541 ERROR [org.radargun.Master] (main) Error in reporter org.radargun.reporting.html.HtmlReporter@16f7c8c1
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.radargun.reporting.html.TimelineDocument.<init>(TimelineDocument.java:64)
	at org.radargun.reporting.html.HtmlReporter.writeTimelineDocuments(HtmlReporter.java:191)
	at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:73)
	at org.radargun.Master.run(Master.java:135)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:34)
```

**Comment by vjuranek** [comment]
Improved exception is logged under #442

**Comment by vjuranek** [comment]
Exception update:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.radargun.reporting.html.TimelineDocument.<init>(TimelineDocument.java:67)
	at org.radargun.reporting.html.HtmlReporter.writeTimelineDocuments(HtmlReporter.java:194)
	at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:75)
	at org.radargun.Master.run(Master.java:140)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:35)
```
