### ISSUE TITLE
Creation of timeline charts sometimes fails

### ISSUE THREAD

**Issue by rmacor** [radargun/radargun#442]
Please see https://jdg-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/perf-cs-marshaller/23/console-edg-perf09-e7ec65ad-3dc6-4873-8b65-7d127efe7e09/ for full log.

ERROR [org.radargun.reporting.html.TimelineDocument] (main) Failed to generate on of the charts: 
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Current timestamp 1481467264825 is bigger then end timestamp 1481467264135
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at org.radargun.reporting.html.TimelineDocument.createTestCharts(TimelineDocument.java:180) [reporter-default-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.reporting.html.HtmlReporter.writeTimelineDocuments(HtmlReporter.java:194) [reporter-default-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:73) [reporter-default-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.Master.run(Master.java:135) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.LaunchMaster.main(LaunchMaster.java:34) [radargun-core-3.0.0-SNAPSHOT.jar:?]
Caused by: java.lang.IllegalStateException: Current timestamp 1481467264825 is bigger then end timestamp 1481467264135
	at org.radargun.reporting.html.TimelineChart.setEvents(TimelineChart.java:100) ~[?:?]
	at org.radargun.reporting.html.TimelineDocument$1.call(TimelineDocument.java:137) ~[?:?]
	at org.radargun.reporting.html.TimelineDocument$1.call(TimelineDocument.java:130) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]

**Comment by vjuranek** [comment]
Closing as it duplicates #434
