### ISSUE TITLE
The CheckCacheDataStage fails in the infinispan90 and jdg71 plugins

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#459]
The `Infinispan70CacheInfo.Cache.getTotalSize` method is implemented using `org.infinispan.iteration.EntryIterable` which has been removed. This causes the following exception:

```
java.lang.NoSuchMethodError: org.infinispan.AdvancedCache.filterEntries(Lorg/infinispan/filter/KeyValueFilter;)Lorg/infinispan/iteration/EntryIterable;
	at org.radargun.service.Infinispan70CacheInfo$Cache.getTotalSize(Infinispan70CacheInfo.java:40)
	at org.radargun.stages.cache.CheckCacheDataStage.executeOnSlave(CheckCacheDataStage.java:217)
	at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:90)
	at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158)
```

**Comment by alanfx** [comment]
https://github.com/radargun/radargun/pull/460

**Comment by mgencur** [comment]
This has been fixed.
