### ISSUE TITLE
NPE in reporter

### ISSUE THREAD

**Issue by rmacor** [radargun/radargun#487]
Occurred in soak tests:
10:06:59,037 ERROR [org.radargun.Master] (main) Error in reporter org.radargun.reporting.html.HtmlReporter@360a3106
java.lang.NullPointerException
	at org.radargun.stats.BasicStatistics.getOperationStatsForGroups(BasicStatistics.java:170)
	at org.radargun.stats.PeriodicStatistics.getOperationStatsForGroups(PeriodicStatistics.java:202)
	at org.radargun.reporting.commons.TestAggregations.addIteration(TestAggregations.java:127)
	at org.radargun.reporting.commons.TestAggregations.<init>(TestAggregations.java:52)
	at org.radargun.reporting.html.HtmlReporter.writeTestReportDocuments(HtmlReporter.java:176)
	at org.radargun.reporting.html.HtmlReporter.run(HtmlReporter.java:77)
	at org.radargun.Master.run(Master.java:140)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:35)

**Comment by rmacor** [comment]
happens with periodic statistics
