### ISSUE TITLE
Rg fails when terminating ISPN, instance being already closed

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#499]
When I run 2 ISPN nodes on the same machine, RG occasionally fails fails during the shutdown with 
```
java.lang.RuntimeException: org.infinispan.IllegalLifecycleStateException: Cache container has been stopped and cannot be reused. Recreate the cache container.
	at org.radargun.service.InfinispanKillableLifecycle.kill(InfinispanKillableLifecycle.java:82) ~[plugin-infinispan51-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.stages.lifecycle.LifecycleHelper.stop(LifecycleHelper.java:166) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.stages.ScenarioDestroyStage.executeOnSlave(ScenarioDestroyStage.java:38) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:90) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158) [radargun-core-3.0.0-SNAPSHOT.jar:?]
Caused by: org.infinispan.IllegalLifecycleStateException: Cache container has been stopped and cannot be reused. Recreate the cache container.
	at org.infinispan.manager.DefaultCacheManager.assertIsNotTerminated(DefaultCacheManager.java:944) ~[infinispan-core-9.2.0.Beta1.jar:9.2.0.Beta1]
	at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:458) ~[infinispan-core-9.2.0.Beta1.jar:9.2.0.Beta1]
	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:454) ~[infinispan-core-9.2.0.Beta1.jar:9.2.0.Beta1]
	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:440) ~[infinispan-core-9.2.0.Beta1.jar:9.2.0.Beta1]
	at org.radargun.service.InfinispanKillableLifecycle.getChannels(InfinispanKillableLifecycle.java:172) ~[plugin-infinispan51-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.Infinispan52Lifecycle.getChannels(Infinispan52Lifecycle.java:22) ~[plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.InfinispanKillableLifecycle.getChannels(InfinispanKillableLifecycle.java:152) ~[plugin-infinispan51-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.InfinispanKillableLifecycle.startDiscarding(InfinispanKillableLifecycle.java:213) ~[plugin-infinispan51-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.InfinispanKillableLifecycle.kill(InfinispanKillableLifecycle.java:69) ~[plugin-infinispan51-3.0.0-SNAPSHOT.jar:?]
	... 4 more
```

**Comment by vjuranek** [comment]
Duplicated #532
