### ISSUE TITLE
InfinispanHotrodService - Failed to retrieve transport factory

### ISSUE THREAD

**Issue by diegolovison** [radargun/radargun#547]
```
09:06:35,129 ERROR [org.radargun.service.InfinispanHotrodService] (MonitorThread-0) Failed to retrieve transport factory
java.lang.NoSuchFieldException: transportFactory
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_171]
	at org.radargun.service.InfinispanHotrodService.getTransportFactory(InfinispanHotrodService.java:77) [plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.InfinispanHotrodService.getValues(InfinispanHotrodService.java:101) [plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.sysmonitor.InternalsMonitor.run(InternalsMonitor.java:34) [radargun-core-3.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by rvansa** [comment]
Yep, that field was dropped. `TransportFactory` ain't used anymoer.

**Comment by diegolovison** [comment]
Yes. I am curious because it was removed in Nov 2017 and it started failing "after" the commit d50be1493b9a9149a38ee56a869444a218207228 in Infinispan.
This commit comes from our daily regression tests. This is why I wrote "after".

**Comment by diegolovison** [comment]
Fixed
