### ISSUE TITLE
NullPointerException when putting data with ISPN926

### ISSUE THREAD

**Issue by diegolovison** [radargun/radargun#590]
java.lang.NullPointerException: null
	at org.radargun.service.HotRodOperations$HotRodCache.put(HotRodOperations.java:83) ~[plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.stages.cache.test.LoadStage$NonTxLoader.loadDataUnit(LoadStage.java:275) [radargun-cache-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.stages.test.LoadStage$Loader.run(LoadStage.java:125) [radargun-core-3.0.0-SNAPSHOT.jar:?]

**Comment by diegolovison** [comment]
It was a failure on my benchmark file. I am closing this issue
